'use strict';

/**
 * 定义ActionType
 */

export const FETCH_RECOMMEND_BANNER = 'FETCH_RECOMMEND_BANNER';
export const FETCH_RECOMMEND_TAG = 'FETCH_RECOMMEND_TAG';
export const FETCH_RECOMMEND = 'FETCH_RECOMMEND';

export const RECEIVE_RECOMMEND_BANNER = 'RECEIVE_RECOMMEND_BANNER';
export const RECEIVE_RECOMMEND_TAG = 'RECEIVE_RECOMMEND_TAG';
export const RECEIVE_RECOMMEND = 'RECEIVE_RECOMMEND'